// scripts/lib/render.js
//
// PURE, OFFLINE. The shared Nunjucks environment and partial-writing helper. Both the
// default build (render-cv.js) and the per-application build (tailor.js) render through
// here, so there is exactly one set of delimiters, one provenance banner format, and one
// place where a template can go wrong.
//
// Nunjucks' default {{ }} / {% %} delimiters collide with LaTeX braces. CLAUDE.md proposed
// \VAR{ } / \BLOCK{ }, but that recipe is Jinja2-only: Nunjucks cannot use "}" as a tag
// terminator (it can't tell a tag-end "}" from a LaTeX "}"). We use << >> for variables and
// <% %> for blocks instead — same intent (LaTeX-safe delimiters), and these never appear in
// LaTeX. Do not revert to \VAR{}.

import nunjucks from 'nunjucks';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { ROOT } from './data.js';

export const env = new nunjucks.Environment(
  new nunjucks.FileSystemLoader(join(ROOT, 'templates')),
  {
    autoescape: false, // LaTeX output, not HTML — never HTML-escape
    trimBlocks: true, // drop the newline right after a <% ... %> tag
    lstripBlocks: true, // drop leading whitespace before a line-leading <% ... %>
    tags: {
      variableStart: '<<',
      variableEnd: '>>',
      blockStart: '<%',
      blockEnd: '%>',
      commentStart: '<#',
      commentEnd: '#>',
    },
  },
);

// Escape text that arrives from a source which is NOT LaTeX — publication titles and venues
// parsed out of the .bib, and cover-letter prose. Hand-authored data/*.json prose is exempt:
// it deliberately contains LaTeX ($\mu$, \&) and is never passed through this filter.
// One regex pass over a map, so an escape introduced by one replacement is never re-escaped.
const TEX_ESCAPES = {
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
  '\\': '\\textbackslash{}',
};
env.addFilter('texesc', (s) =>
  String(s ?? '').replace(/[&%$#_{}~^\\]/g, (c) => TEX_ESCAPES[c]),
);

// Strip LaTeX back to readable plain text, for the cover letter's .txt twin.
env.addFilter('untex', (s) =>
  String(s ?? '')
    .replace(/\\textbar\{\}/g, '|')
    .replace(/\\(?:textbf|textit|emph|text)\{([^}]*)\}/g, '$1')
    .replace(/\$\\mu\$/g, 'µ')
    .replace(/\\times/g, 'x')
    .replace(/\\&/g, '&')
    .replace(/\\%/g, '%')
    .replace(/\\\$/g, '$')
    .replace(/\\_/g, '_')
    .replace(/\\#/g, '#')
    .replace(/---/g, '—')
    .replace(/\$/g, '')
    .trim(),
);

// Every generated file says, in its first lines, what wrote it and what to edit instead.
// A generated file that doesn't announce itself eventually gets hand-edited.
export const header = (
  template,
  src,
  { script = 'render-cv.js', comment = '%', cmd = 'npm run render' } = {},
) =>
  [
    `${comment} GENERATED by scripts/${script} — DO NOT EDIT BY HAND.`,
    `${comment} Source: ${src} via templates/${template}. Run \`${cmd}\`.`,
    '',
  ].join('\n');

/**
 * Render one template to one output file, prefixed with the provenance banner.
 * Creates the output directory when missing (tailored builds write into per-application
 * subdirectories that don't exist yet).
 *
 * `banner: false` suppresses the provenance header. Used for the cover letter's .txt twin,
 * which exists to be pasted into an application form — a comment banner at the top of it
 * would eventually be pasted along with the letter.
 */
export function renderPartial({
  template,
  out,
  context,
  src,
  script,
  cmd,
  comment = '%',
  banner = true,
}) {
  const body = env.render(template, context);
  const abs = join(ROOT, out);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, (banner ? header(template, src, { script, comment, cmd }) : '') + body, 'utf8');
  console.log(`wrote ${out}`);
  return out;
}
