// SOURCE — you own this file. Edit freely, by hand or by agent.
//
// scripts/lib/render.js
//
// PURE, OFFLINE. The shared Nunjucks environment and partial-writing helper. Both the
// default build (render-cv.js) and the per-application build (tailor.js) render through
// here, so there is exactly one set of delimiters, one provenance banner format, and one
// place where a template can go wrong.
//
// Nunjucks' default {{ }} / {% %} delimiters collide with LaTeX braces. CLAUDE.md proposed
// \VAR{ } / \BLOCK{ }, but that recipe is Jinja2-only: Nunjucks cannot use "}" as a tag
// terminator (it can't tell a tag-end "}" from a LaTeX "}"). We use << >> for variables and
// <% %> for blocks instead — same intent (LaTeX-safe delimiters), and these never appear in
// LaTeX. Do not revert to \VAR{}.

import nunjucks from 'nunjucks';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { ROOT } from './data.js';

export const env = new nunjucks.Environment(
  new nunjucks.FileSystemLoader(join(ROOT, 'cv', 'templates')),
  {
    autoescape: false, // LaTeX output, not HTML — never HTML-escape
    trimBlocks: true, // drop the newline right after a <% ... %> tag
    lstripBlocks: true, // drop leading whitespace before a line-leading <% ... %>
    tags: {
      variableStart: '<<',
      variableEnd: '>>',
      blockStart: '<%',
      blockEnd: '%>',
      commentStart: '<#',
      commentEnd: '#>',
    },
  },
);

// Escape text that arrives from a source which is NOT LaTeX — publication titles and venues
// parsed out of the .bib, and cover-letter prose. Hand-authored data/*.json prose is exempt:
// it deliberately contains LaTeX ($\mu$, \&) and is never passed through this filter.
// One regex pass over a map, so an escape introduced by one replacement is never re-escaped.
const TEX_ESCAPES = {
  '&': '\\&',
  '%': '\\%',
  $: '\\$',
  '#': '\\#',
  _: '\\_',
  '{': '\\{',
  '}': '\\}',
  '~': '\\textasciitilde{}',
  '^': '\\textasciicircum{}',
  '\\': '\\textbackslash{}',
};
env.addFilter('texesc', (s) =>
  String(s ?? '').replace(/[&%$#_{}~^\\]/g, (c) => TEX_ESCAPES[c]),
);

// One line of the Skills column, e.g.
//   \mbox{Remote Sensing}\discretionary{}{}{|}\mbox{Geosciences}
//
// That column is 0.33\textwidth — narrow enough that TeX's defaults made a mess of it:
// automatic hyphenation split labels mid-word ("Earth Foundation Mod-els", "Google Earth
// En-gine") and labels containing a hyphen broke at it ("Time-" / "series modelling"). Both
// read as typos rather than as line breaks.
//
// So each label is an \mbox — unbreakable, whatever is inside it — and the only break TeX is
// offered is at the separator, which is where a reader already sees a boundary.
//
// The separator is a \discretionary rather than a literal "|": it prints when the line holds
// together and vanishes when the break is taken, so no line ends on a stranded pipe. The three
// arguments are {before-break}{after-break}{unbroken} — all three matter, and leaving the
// first two empty is what makes the pipe disappear at a line end.
//
// The failure mode this trades into: a single label wider than the column can no longer be
// broken, so it overflows instead of wrapping. Measured against the real class, the column is
// 179.2pt and the longest label today is "Machine Learning & Deep Learning" at 148.9pt, so
// there is ~30pt of headroom. A label longer than that needs splitting in data/skills.json.
env.addFilter('skillline', (items) =>
  (items ?? []).map((i) => `\\mbox{${i.label}}`).join('\\discretionary{}{}{|}'),
);

// Strip LaTeX back to readable plain text, for the cover letter's .txt twin.
env.addFilter('untex', (s) =>
  String(s ?? '')
    .replace(/\\textbar\{\}/g, '|')
    .replace(/\\(?:textbf|textit|emph|text)\{([^}]*)\}/g, '$1')
    .replace(/\$\\mu\$/g, 'µ')
    .replace(/\\times/g, 'x')
    .replace(/\\&/g, '&')
    .replace(/\\%/g, '%')
    .replace(/\\\$/g, '$')
    .replace(/\\_/g, '_')
    .replace(/\\#/g, '#')
    .replace(/---/g, '—')
    .replace(/\$/g, '')
    .trim(),
);

// Every generated file says, in its first lines, what wrote it and what to edit instead.
// A generated file that doesn't announce itself eventually gets hand-edited.
export const header = (
  template,
  src,
  { script = 'render-cv.js', comment = '%', cmd = 'npm run render' } = {},
) =>
  [
    `${comment} GENERATED by scripts/${script} — DO NOT EDIT BY HAND.`,
    `${comment} Source: ${src} via cv/templates/${template}. Run \`${cmd}\`.`,
    '',
    // Trailing blank line, so every partial looks the same regardless of whether its template
    // happens to open with a `<# … #>` comment. A leading blank line in an \input'd file is a
    // no-op in TeX (a \par with no paragraph in progress does nothing).
    '',
  ].join('\n');

/**
 * Render one template to one output file, prefixed with the provenance banner.
 * Creates the output directory when missing (tailored builds write into per-application
 * subdirectories that don't exist yet).
 *
 * `banner: false` suppresses the provenance header. Used for the cover letter's .txt twin,
 * which exists to be pasted into an application form — a comment banner at the top of it
 * would eventually be pasted along with the letter.
 */
export function renderPartial({
  template,
  out,
  context,
  src,
  script,
  cmd,
  comment = '%',
  banner = true,
}) {
  // Strip leading blank lines. A template's own `<# … #>` header comment renders as nothing
  // but leaves its trailing newline behind, so a comment added for the reader's benefit would
  // otherwise change the generated output. Documentation must not move bytes.
  const body = env.render(template, context).replace(/^\s*\n/, '');
  const abs = join(ROOT, out);
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, (banner ? header(template, src, { script, comment, cmd }) : '') + body, 'utf8');
  console.log(`wrote ${out}`);
  return out;
}
