// scripts/render-cv.js
//
// PURE, OFFLINE. Renders shared prose (currently the Experience section) from
// data/experience.json into per-CV LaTeX partials via Nunjucks, so the same facts feed
// both PDFs (and the website) from one source. The .tex shells \input the generated
// partials; the generated files are script-written and must never be hand-edited.
//
// Nunjucks' default {{ }} / {% %} delimiters collide with LaTeX braces. CLAUDE.md proposed
// \VAR{ } / \BLOCK{ }, but that recipe is Jinja2-only: Nunjucks cannot use "}" as a tag
// terminator (it can't tell a tag-end "}" from a LaTeX "}"). We use << >> for variables and
// <% %> for blocks instead — same intent (LaTeX-safe delimiters), and these never appear in
// LaTeX. Two distinct templates keep the two CV layouts separate — only the data is shared.

import nunjucks from 'nunjucks';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { loadData, ROOT } from './lib/data.js';

const env = new nunjucks.Environment(
  new nunjucks.FileSystemLoader(join(ROOT, 'templates')),
  {
    autoescape: false, // LaTeX output, not HTML — never HTML-escape
    trimBlocks: true, // drop the newline right after a \BLOCK{...} tag
    lstripBlocks: true, // drop leading whitespace before a line-leading \BLOCK{...}
    tags: {
      variableStart: '<<',
      variableEnd: '>>',
      blockStart: '<%',
      blockEnd: '%>',
      commentStart: '<#',
      commentEnd: '#>',
    },
  },
);

const { experience } = loadData();

const header = (script) =>
  [
    '% GENERATED by scripts/render-cv.js — DO NOT EDIT BY HAND.',
    `% Source: data/experience.json via templates/${script}. Run \`npm run render\`.`,
    '',
  ].join('\n');

const jobs = [
  {
    template: 'onepage-experience.tex.njk',
    out: 'cv/onepage/generated/experience.tex',
  },
  {
    template: 'biosketch-experience.tex.njk',
    out: 'cv/biosketch/generated/experience.tex',
  },
];

for (const { template, out } of jobs) {
  const rendered = env.render(template, { experience });
  writeFileSync(join(ROOT, out), header(template) + rendered, 'utf8');
  console.log(`wrote ${out}`);
}
