// scripts/render-cv.js
//
// PURE, OFFLINE. Renders shared prose (currently the Experience section) from
// data/experience.json into per-CV LaTeX partials via Nunjucks, so the same facts feed
// both PDFs (and the website) from one source. The .tex shells \input the generated
// partials; the generated files are script-written and must never be hand-edited.
//
// Nunjucks' default {{ }} / {% %} delimiters collide with LaTeX braces. CLAUDE.md proposed
// \VAR{ } / \BLOCK{ }, but that recipe is Jinja2-only: Nunjucks cannot use "}" as a tag
// terminator (it can't tell a tag-end "}" from a LaTeX "}"). We use << >> for variables and
// <% %> for blocks instead — same intent (LaTeX-safe delimiters), and these never appear in
// LaTeX. Two distinct templates keep the two CV layouts separate — only the data is shared.

import nunjucks from 'nunjucks';
import { readFileSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { loadData, ROOT } from './lib/data.js';

const env = new nunjucks.Environment(
  new nunjucks.FileSystemLoader(join(ROOT, 'templates')),
  {
    autoescape: false, // LaTeX output, not HTML — never HTML-escape
    trimBlocks: true, // drop the newline right after a \BLOCK{...} tag
    lstripBlocks: true, // drop leading whitespace before a line-leading \BLOCK{...}
    tags: {
      variableStart: '<<',
      variableEnd: '>>',
      blockStart: '<%',
      blockEnd: '%>',
      commentStart: '<#',
      commentEnd: '#>',
    },
  },
);

const { experience } = loadData();

const header = (script, src = 'data/experience.json') =>
  [
    '% GENERATED by scripts/render-cv.js — DO NOT EDIT BY HAND.',
    `% Source: ${src} via templates/${script}. Run \`npm run render\`.`,
    '',
  ].join('\n');

// ── Phase D: job-tailored one-pager ───────────────────────────────────────────
// `APP=applications/<file>.json npm run render` renders a TAILORED one-pager from a
// proposed selection manifest, instead of the default render. The manifest only ever
// SELECTS/REPHRASES facts already in data/experience.json (Invariant 6 — the model never
// mints facts). The canonical ONE-PAGE.tex is left untouched; a variant shell is emitted
// that \inputs the tailored experience, so the original keeps building unchanged.
if (process.env.APP) {
  const appRel = process.env.APP;
  const app = JSON.parse(readFileSync(join(ROOT, appRel), 'utf8'));
  const id = `tailored-${basename(appRel).replace(/\.json$/, '')}`;

  const expOut = `cv/onepage/generated/${id}.experience.tex`;
  const expTex = env.render('onepage-experience.tex.njk', { experience: app.experience });
  writeFileSync(join(ROOT, expOut), header('onepage-experience.tex.njk', appRel) + expTex, 'utf8');

  // Variant shell: copy of ONE-PAGE.tex that points at the tailored experience partial.
  const shell = readFileSync(join(ROOT, 'cv/onepage/ONE-PAGE.tex'), 'utf8').replace(
    '\\input{generated/experience.tex}',
    `\\input{generated/${id}.experience.tex}`,
  );
  const shellOut = `cv/onepage/${id}.tex`;
  writeFileSync(join(ROOT, shellOut), shell, 'utf8');

  console.log(`wrote ${expOut}`);
  console.log(`wrote ${shellOut}  (compile this for the tailored one-pager)`);
  process.exit(0);
}

const jobs = [
  {
    template: 'onepage-experience.tex.njk',
    out: 'cv/onepage/generated/experience.tex',
  },
  {
    template: 'biosketch-experience.tex.njk',
    out: 'cv/biosketch/generated/experience.tex',
  },
];

for (const { template, out } of jobs) {
  const rendered = env.render(template, { experience });
  writeFileSync(join(ROOT, out), header(template) + rendered, 'utf8');
  console.log(`wrote ${out}`);
}
